### ISSUE TITLE
Auto-start + kill-switch

### ISSUE THREAD

**Issue by acollien** [amussey/FreeNAS-Transmission-OpenVPN#10]
Can you include the step for the following in your readMe please:
1. Auto-start openvpn on jail/plugin start (unless that's already the case? the script and guide are ambiguous)
2. Kill-switch setup (so transmission loses network connection if open vpn drops)
3. Steps to change the openvpn server country
4. Is there a way to test that the vpn is working?

Thanks so much.

**Comment by amussey** [comment]
Hi @acollien, I'll update the README in a bit, but to answer your questions:
1. **Auto start**: Once the VPN is set up through the `Makefile`, everything should auto-start when you boot FreeNAS.
2.  **Kill Switch**: While a little bit primitive (relies on OpenVPN doing it's job), a kill switch is built in.  In [`run.sh.template`](https://github.com/amussey/FreeNAS-Transmission-OpenVPN/blob/master/run.sh.template), OpenVPN is configured to call `stop_transmission.sh` when the VPN connection is lost (`--down`).
3. **Changing Country**:  This will depend on which OpenVPN configuration file you use.  In the step:  `mv Sweden.ovpn openvpn.conf`, you can change the country by selecting another `ovpn` file.  You can list the available files/countries by running the command `ls *.ovpn`.
4. **Testing**: The easiest way is to use this torrent from TorGuard to check the IP address your torrents are connecting from: https://torguard.net/checkmytorrentipaddress.php  Compare this against your local machine's IP: http://www.myipaddress.com/show-my-ip-address/

Let me know if you have any more issues!

**Comment by amussey** [comment]
Added the answers to some of these questions into the README.md in commit 3ed8f53.
