### ISSUE TITLE
OpenVPN looses connection

### ISSUE THREAD

**Issue by MrSnuggles** [amussey/FreeNAS-Transmission-OpenVPN#2]
Hey, thank you for your work!
From time to time i have the problem that the VPN connection fails, what is pretty bad.
The lasttime the transmission jail went to an off state.
It is possible to only allow the connection via VPN?

**Comment by amussey** [comment]
Yep, there definitely is.  The best way to do this would be through `ipfw` or `iptables` firewall rules.  There are a couple other guides for OpenVPN + Transmission that explain how to set up this sort of thing.  [Here's one](http://askubuntu.com/questions/583679/transmission-daemon-over-openvpn-on-a-beagleboard-arm-sbc), and [here's another with ipfw](https://forums.freenas.org/index.php?threads/how-to-use-openvpn-ipfw-in-a-jail-so-it-only-connects-to-the-vpn.18669/).

**Comment by MrSnuggles** [comment]
Thank you very much! i very appreciate it.
