### ISSUE TITLE
Verify that it works

### ISSUE THREAD

**Issue by evdtempel** [amussey/FreeNAS-Transmission-OpenVPN#5]
Hey there, thanks for this project! Very easy to setup!

I have but one question: how do I verify that my VPN-connection works and all traffic gets routed through there? There is no way to see something like the external IP in the transmission web interface. The only indication I have is that my listening port is now shown as closed. 

Kind regards

**Comment by amussey** [comment]
Glad to hear things are working!

I'd highly recommend this torrent for checking the external IP address of your client:
http://torguard.net/checkmytorrentipaddress.php

**Comment by evdtempel** [comment]
Cool, it seems to be working great and routing all traffic through the PIA VPN! Thanks :+1:
