### ISSUE TITLE
Error when installing openVPN

### ISSUE THREAD

**Issue by maxxxxpower** [amussey/FreeNAS-Transmission-OpenVPN#6]
pkg: No packages available to install matching 'openvpn' have been found in the repositories

**Comment by amussey** [comment]
Hi @maxxxxpower, what version of FreeNAS are you running?

**Comment by maxxxxpower** [comment]
Version 9.3, amd64 bit. The weird thing is I get an error when trying to add git as well. File not found, no access.

I had wiped out the Transmission jail last week and rebuilt it without issue. Is there no longer an OpenvPN package available? Not sure what I am doing wrong, as I have had this working before!

**Comment by maxxxxpower** [comment]
I'll close this. Blew the whole jail out, rebooted and reinstalled, and now it's working again. Weird!

Thanks for the fast response in any case.

**Comment by amussey** [comment]
Excellent, glad you've got it working! :+1:
